# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "pyro2927"
description: >
  Random ramblings

email: joseph@pintozzi.com
logo:
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Joe Pintozzi'
author: 'Joe Pintozzi'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://pyro2927.github.io"
baseurl: ""

social:
  - icon:	twitter
    url:	https://twitter.com/pyro2927
    desc: Follow me on twitter
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/pyro2927
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
